[package]
name = "bspparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.9"
json = "0.12.4"
thiserror = "1.0.57"
lzma-rs={version="^0.3.0", features=["stream"]}
